# Generated by Django 3.2 on 2021-04-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HashGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UrlKeeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.URLField(verbose_name='Your Url')),
                ('shortened', models.URLField()),
            ],
        ),
    ]
